// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS4Bt6EHVSNyblxgPyujbCp3eFbUo5PRo',
    appId: '1:16736783895:web:325dc6decb04ad6186d652',
    messagingSenderId: '16736783895',
    projectId: 'cmsc23-b6l',
    authDomain: 'cmsc23-b6l.firebaseapp.com',
    storageBucket: 'cmsc23-b6l.appspot.com',
    measurementId: 'G-H78GZGXCMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnGgFaXQpM-NKkzpnKPWfWpJqG1U2jE28',
    appId: '1:16736783895:android:999ffd23dca4cd2486d652',
    messagingSenderId: '16736783895',
    projectId: 'cmsc23-b6l',
    storageBucket: 'cmsc23-b6l.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGt4nMQsyboB-3GGYHnzxz3owyDpt18yE',
    appId: '1:16736783895:ios:74c685f189318fa286d652',
    messagingSenderId: '16736783895',
    projectId: 'cmsc23-b6l',
    storageBucket: 'cmsc23-b6l.appspot.com',
    iosClientId: '16736783895-h18knbhflgl3udg1f6g7h2ds3jafbgpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGt4nMQsyboB-3GGYHnzxz3owyDpt18yE',
    appId: '1:16736783895:ios:74c685f189318fa286d652',
    messagingSenderId: '16736783895',
    projectId: 'cmsc23-b6l',
    storageBucket: 'cmsc23-b6l.appspot.com',
    iosClientId: '16736783895-h18knbhflgl3udg1f6g7h2ds3jafbgpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectApp',
  );
}
